# Generated by Django 4.0.5 on 2022-07-07 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_alter_featured_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featured',
            name='pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Users.projects'),
        ),
    ]
