# Generated by Django 4.0.5 on 2022-07-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='profile_img',
            field=models.ImageField(default='default.jpg', upload_to='media', verbose_name='photo'),
        ),
    ]
